//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalBlog.App.Cultures {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PersonalBlog.App.Cultures.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Button_Back {
            get {
                return ResourceManager.GetString("Button_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Button_Close {
            get {
                return ResourceManager.GetString("Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Button_No {
            get {
                return ResourceManager.GetString("Button_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Button_Submit {
            get {
                return ResourceManager.GetString("Button_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Button_Yes {
            get {
                return ResourceManager.GetString("Button_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Field_Login_Password {
            get {
                return ResourceManager.GetString("Field_Login_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string Field_Login_UserName {
            get {
                return ResourceManager.GetString("Field_Login_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name.
        /// </summary>
        public static string Field_Post_Category_Name {
            get {
                return ResourceManager.GetString("Field_Post_Category_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Content.
        /// </summary>
        public static string Field_Post_Content {
            get {
                return ResourceManager.GetString("Field_Post_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Title.
        /// </summary>
        public static string Field_Post_Title {
            get {
                return ResourceManager.GetString("Field_Post_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of category.
        /// </summary>
        public static string Input_Category_Name_Placeholder {
            get {
                return ResourceManager.GetString("Input_Category_Name_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sort number of category from small to large.
        /// </summary>
        public static string Input_Category_SortNo_Placeholder {
            get {
                return ResourceManager.GetString("Input_Category_SortNo_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please write your content here...Markdown Support Only!!!.
        /// </summary>
        public static string Input_Post_Content_Placeholder {
            get {
                return ResourceManager.GetString("Input_Post_Content_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your title.
        /// </summary>
        public static string Input_Post_Title_Placeholder {
            get {
                return ResourceManager.GetString("Input_Post_Title_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Message_Category_Table_Id {
            get {
                return ResourceManager.GetString("Message_Category_Table_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Message_Category_Table_Name {
            get {
                return ResourceManager.GetString("Message_Category_Table_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort No..
        /// </summary>
        public static string Message_Category_Table_SortNo {
            get {
                return ResourceManager.GetString("Message_Category_Table_SortNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to do this action?.
        /// </summary>
        public static string Message_ConfirmAction {
            get {
                return ResourceManager.GetString("Message_ConfirmAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Message_Delete {
            get {
                return ResourceManager.GetString("Message_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Message_Edit {
            get {
                return ResourceManager.GetString("Message_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login is failed..
        /// </summary>
        public static string Message_Login_Invalid {
            get {
                return ResourceManager.GetString("Message_Login_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Category.
        /// </summary>
        public static string Message_NewCategory {
            get {
                return ResourceManager.GetString("Message_NewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Post.
        /// </summary>
        public static string Message_NewPost {
            get {
                return ResourceManager.GetString("Message_NewPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, There is no data here....
        /// </summary>
        public static string Message_NoData {
            get {
                return ResourceManager.GetString("Message_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The submit is invalid..
        /// </summary>
        public static string Message_SubmitError {
            get {
                return ResourceManager.GetString("Message_SubmitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit is successful.
        /// </summary>
        public static string Message_SubmitSuccess {
            get {
                return ResourceManager.GetString("Message_SubmitSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation.
        /// </summary>
        public static string Message_Table_Operation {
            get {
                return ResourceManager.GetString("Message_Table_Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Page_Categories {
            get {
                return ResourceManager.GetString("Page_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string Page_Category_All {
            get {
                return ResourceManager.GetString("Page_Category_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Page_Create {
            get {
                return ResourceManager.GetString("Page_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string Page_Detail {
            get {
                return ResourceManager.GetString("Page_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Page_Edit {
            get {
                return ResourceManager.GetString("Page_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Page_Login {
            get {
                return ResourceManager.GetString("Page_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Setting.
        /// </summary>
        public static string Page_Setting {
            get {
                return ResourceManager.GetString("Page_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Configuration.
        /// </summary>
        public static string Page_Setting_Admin {
            get {
                return ResourceManager.GetString("Page_Setting_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Configuration.
        /// </summary>
        public static string Page_Setting_Site {
            get {
                return ResourceManager.GetString("Page_Setting_Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SignOut.
        /// </summary>
        public static string Page_SignOut {
            get {
                return ResourceManager.GetString("Page_SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required..
        /// </summary>
        public static string Validate_Field_Required {
            get {
                return ResourceManager.GetString("Validate_Field_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field of {0} has limited in {1} length of string.
        /// </summary>
        public static string Validate_Field_StringLength {
            get {
                return ResourceManager.GetString("Validate_Field_StringLength", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Sorry, You do not have permission.
        /// </summary>
        public static string Message_NotAuthorized
        {
            get
            {
                return ResourceManager.GetString("Message_NotAuthorized", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        public static string Field_Top
        {
            get
            {
                return ResourceManager.GetString("Field_Top", resourceCulture);
            }
        }
    }
}
